# This is a basic workflow that is manually triggered

name: Create release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: start release
        run: |
          git checkout develop
          git checkout -b release/<version number>
          git flow start release

      - name: commit
        run: |
          # Change version number, commit and push
          git add ./Formplot/Formplot.csproj
          git commit -m "feat: Raises version number"
          
      - name: finish release
        run: |
          git checkout master
          git merge release/<version number>
          git tag <version number>
          git branch -d release/versionnumber
          git checkout develop
          git merge master
          
      - name: push
        run: |
          git checkout develop
          git push origin develop
          git checkout master
          git push origin master
          git push --tags
      
