# Calls a workflow that
# + builds and tests the develop branch,
# + packs and uploads a beta NuGet package.
#
# This workflow runs automatically on pushes or pull requests to develop.

name: Build, test & pack beta on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: ZEISS-PiWeb/github-actions/.github/workflows/develop.yml@main
    with:
      do_pack: true  
    secrets: inherit
